# Generated by Django 4.2.5 on 2023-10-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTMSApp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistration',
        ),
    ]
