# Generated by Django 4.2.5 on 2023-10-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTMSApp', '0003_delete_userregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='last_name',
        ),
    ]
