# Generated by Django 4.2.5 on 2023-10-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTMSApp', '0004_rename_fname_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='name',
        ),
    ]
