# Generated by Django 4.2.5 on 2023-10-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTMSApp', '0005_rename_first_name_student_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='last_name',
        ),
    ]
