# Generated by Django 4.2.5 on 2023-10-01 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PTMSApp', '0006_rename_fname_student_first_name_and_more'),
    ]

    operations = [
    ]
