# Generated by Django 4.2.5 on 2023-10-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PTMSApp', '0007_auto_20231001_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
